testnet:
  DNS: AS12MGDGVB3xNDqzGidJM5fcAbjF1ZP5XAecm5ww4RU7sfQd4cMKk
  URLs:
    - https://test.massa.net/api/v2

buildnet:
  DNS: AS12tsy5TtDyGsWggDvqDLagxZqkuTiTPqWhqmrx7KSQNJwQSbnBA #AS12quYbKSv91DZoz6jL9QEswpqhsYhwYv4mt9XFXC5rx7Kww3DEH
  URLs:
    - https://buildnet.massa.net/api/v2
  Default: true

labnet:
  DNS: AS1PV17jWkbUs7mfXsn8Xfs9AK6tHiJoxuGu7RySFMV8GYdMeUSh
  URLs:
    - 192.168.2.1
    - 192.168.2.2
